'''
# Limits
'''
MAX_GLOBAL_DIFFICULTY = 100000
MAX_NODE_DIFFICULTY = 5000
MAX_INTEGRAL_LEVEL = 20

'''
# Algebraics
'''
ALGEBRAIC_STEP_DIFFICULTY = 10
SOLVE_STEP_DIFFICULTY = 20
SIMPLIFY_STEP_DIFFICULTY = 20
EXPAND_STEP_DIFFICULTY = 20
FACTOR_STEP_DIFFICULTY = 20
SUBSTITUTION_STEP_DIFFICULTY = 20

'''
# Integrals
'''
INTEGRATION_MAX_DIFFICULTY = 50
ATOMIC_INTEGRAL_DIFFICULTY = 60
RECURSIVE_INTEGRAL_DIFFICULTY = 20
SYMPY_INTEGRAL = 70
